# Generated by Django 2.1.5 on 2020-09-13 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='department',
        ),
    ]
